#დავალება1

for i in range(21):
    print(i)

#დავალება2

for i in range(1,11):
    print(i)

#დავალება3

for i in range(0,101,2):
    print(i)

for i in range(1,101,2)
    print(i)

#დავალება4

num = int(input("enter number")) 
for i in range(num):
    print(i)

#დავალება5

for i in range(50,5):
    print(i)

#while loop

#დავალება1

for i in range(0,21,2):
    print(i)

#დავალება2

for i in range(1,11):
    print(i)

#დავალება3

my_num = 7 
your_num = int(input("enter number"))
while your_num

    


